Hackathon/urls.py
from django.contrib import admin
from django.urls import path
from sistemas.forms import CustomAuthenticationForm
from django.contrib.auth import views as auth_views
from sistemas.views import dashboard_view
from sistemas.views import comunicacion_view
from sistemas.views import registro_view
from sistemas.views import tickets_view, tickets_view5,tickets_view6, tickets_view1
from sistemas.views import tickets_view2, tickets_view3, tickets_view4
from sistemas.views import send_test_email, grafica1, grafica2


urlpatterns = [
    path('', auth_views.LoginView.as_view(authentication_form=CustomAuthenticationForm), name='login'),
    path('detalles/', tickets_view, name='detalle_ticket'),
    path('send-email/', send_test_email ),
    path('dashboards/contenido2.html', grafica2),
    path('dashboards/contenido1.html', grafica1),
    path('detalles/contenido1.html',tickets_view1),
    path('detalles/contenido2.html',tickets_view2),
    path('detalles/contenido3.html',tickets_view3),
    path('detalles/contenido4.html',tickets_view4),
    path('detalles/contenido5.html',tickets_view5),
    path('detalles/contenido6.html',tickets_view6),
    path('tickets/', registro_view, name='tickets'),
    path('comunicacion/',comunicacion_view, name = 'comunicacion'),
    path('dashboards/', dashboard_view, name='dashboard'),
    path('admin/', admin.site.urls, name = admin),
]

sistemas/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=20, verbose_name='Nombre')
    last_name = models.CharField(max_length=20, verbose_name='Apellido')
    email = models.EmailField(verbose_name='Correo electronico')
    username = models.CharField(verbose_name='Usuario', max_length=20, unique=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


class FailedLoginAttempt(models.Model):
    username = models.CharField(max_length=20, verbose_name='Usuario')
    ip_address = models.GenericIPAddressField(verbose_name='IP')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')

    def __str__(self):
        return f"{self.username} at {self.timestamp}"

    class Meta:
        verbose_name = 'Registro de intentos fallidos de inicio de sesion'
        verbose_name_plural = 'Registros de intentos fallidos de inicio de sesion'


class RiskLog(models.Model):
    RISK_LEVEL_CHOICES = (
        ('low', 'Riesgo bajo'),
        ('medium', 'Riesgo medio'),
        ('high', 'Riesgo alto'),
    )

    STATUS_CHOICES = (
        ('Pending', 'Pendiente'),
        ('Assigned', 'Asignado'),
        ('Resuelto','Reasignado'),
    )

    username = models.CharField(max_length=20, verbose_name='Usuario')
    ip_address = models.GenericIPAddressField(verbose_name='IP')
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    risk_level = models.CharField(choices=RISK_LEVEL_CHOICES, verbose_name='Nivel de riesgo')
    description = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='unassigned', verbose_name='Estado')

    class Meta:
        verbose_name_plural = 'Logs de riesgos'
        verbose_name = 'Log de riesgo'

    def __str__(self):
        return f"{self.risk_level} risk at {self.timestamp} by {self.username}"


class LogEntry(models.Model):
    line_id = models.AutoField(primary_key=True)
    date = models.DateField()
    time = models.CharField(max_length=12)
    level = models.CharField(max_length=255)
    process = models.CharField(max_length=255)
    component = models.CharField(max_length=255)
    content = models.TextField()
    event_id = models.CharField(max_length=50)
    event_template = models.TextField()


    @property
    def risk_level(self):
        level_mapping = {
            'WARNING': 'Riesgo bajo',
            'ERROR': 'Riesgo medio',
            'FATAL': 'Riesgo alto',
        }
        return level_mapping.get(self.level,'unknown')
    def __str__(self):
        return f"{self.line_id} - {self.level}"





templates/base.html
<!DOCTYPE html>
<!-- Coding by CodingNepal | www.codingnepalweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Drop Down Sidebar Menu </title>
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link href="https://assets.codepen.io/344846/style.css" rel="stylesheet"><link rel="stylesheet" href="./style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400..700;1,400..700&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

      {% load static %}
    <link rel="stylesheet" href="{% static 'css/navBar.css' %}">
      <link rel="stylesheet" href="{% static 'css/dashBoard.css' %}">
      <link rel="stylesheet" href="{% static 'css/comunicacion.css' %}">
      <link rel="stylesheet" href="{% static 'css/ticket.css'%}">
      <link rel="stylesheet" href="{% static 'css/dashboard2.css'%}">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

   </head>

<body>
  <div class="sidebar close">
    <div class="logo-details">
      <a href="https://imgbb.com/"><img src="https://i.ibb.co/3ydQZJS/logo.png" alt="logo" border="0" /></a>
    </div>
    <ul class="nav-links">
      <li>
        <a href="{% url 'dashboard' %}">
          <i class='bx bx-line-chart' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Dashboard</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'tickets' %}">
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Security Incidents</span>
        </a>
        <ul class="sub-menu blank">
          <li>
            <a class="link_name" href="#">Security Incidents</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="{% url 'comunicacion' %}">
          <i class='bx bx-bell' ></i>
          <span class="link_name">Notifications</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Notifications</a></li>
        </ul>
      </li>
      <li>
        <a href="{% url 'detalle_ticket' %}">
          <i class='bx bx-bell' ></i>
          <span class="link_name">Setting</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Setting</a></li>
        </ul>
      </li>
      
    <div class="profile-details">
      <i class="bx bx-user-circle" id="profile"></i>
      <div class="name-job">
        <div class="profile_name">Prem Shahi</div>
        <div class="job">Web Desginer</div>
      </div>
      <i class='bx bx-log-out' id="log_out"></i>
    </div>
  </li>
</ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
      <span class="text">SGIS</span>
    </div>
      {% block contenido %}{% endblock contenido %}
  </section>
  <script>
  let arrow = document.querySelectorAll(".arrow");
  for (var i = 0; i < arrow.length; i++) {
    arrow[i].addEventListener("click", (e)=>{
   let arrowParent = e.target.parentElement.parentElement;//selecting main parent of arrow
   arrowParent.classList.toggle("showMenu");
    });
  }
  let sidebar = document.querySelector(".sidebar");
  let sidebarBtn = document.querySelector(".bx-menu");
  console.log(sidebarBtn);
  sidebarBtn.addEventListener("click", ()=>{
    sidebar.classList.toggle("close");
  });
  </script>
</body>
</html>

templates/contenido2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Logins</title>
    <style>
       
        #estadoServidor {
            font-style: oblique;
            color: rgb(21, 75, 34);
        }

        #contenedorTabla {
            width: 100%; /* Ajusta el ancho del contenedor al ancho de la ventana */
            max-height: 280px; /* Altura máxima del contenedor */
            overflow-y: auto; /* Habilita la barra de desplazamiento vertical si el contenido excede la altura máxima */
            display: flex;
            justify-content: center;
            margin-top: 3%;
        }

        table {
            width: 90%; /* Anchura de la tabla, asegura un margen a los lados dentro del contenedor */
            border-collapse: collapse;
        }

        th, td {
            text-align: center; /* Alinea el texto de las celdas al centro */
            
            
            padding: 8px; /* Espaciado interno para texto en th y td */
        }

        th {
            background-color: rgb(123, 70, 61);
            font-size: 20px;
            color: white;
            height: 50px; /* Altura fija para los encabezados de columna */
        }

        td {
            height: 60px;
            min-height: 70px; /* Altura mínima para las celdas de datos, asegura uniformidad */
        }

        tr:nth-child(odd) {
            background-color: #f2f2f2; /* Gris claro para filas impares */
        }

        tr:nth-child(even) {
            background-color: #e6e6e6; /* Otro tono de gris para filas pares */
        }
    </style>
</head>
<body>
    <div id="contenedorTabla">
        <table>
            <thead>
                        <tr id="cabezeraTabla1">
                            <th>Nivel Riesgo</th>
                            <th>Fecha</th>
                            <th>Dirección IP</th>
                            <th>Descripcion</th>
                        </tr>
            </thead>
            <tbody>
                        {% for log in recent_logs %}
                        <tr>
                            <td>{{ log.get_risk_level_display }}</td>
                            <td>{{ log.timestamp|date:"d F" }}</td>
                            <td>{{ log.ip_address }}</td>
                            <td>{{ log.description }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">No recent logs found.</td>
                        </tr>
                        {% endfor %}
                <!-- Repite las filas según sea necesario para demostrar el scroll -->
                <!-- Agregar más datos ficticios para llenar la tabla y activar el scrollbar -->
            </tbody>
        </table>
    </div>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block contenido %}

    <div id="contendorMain">

      <div class="contenedorGraficas">

        <div class="carrusel">
            <div class="grafica">
                <canvas id="myChart"></canvas>
            </div>
            <div class="grafica">
                <canvas id="myChart2"></canvas>
            </div>
            <div class="grafica">
                <canvas id="myChart3"></canvas>
            </div>
            <div class="grafica">
                <canvas id="myChart4"></canvas>
            </div>
        </div>

    </div>
        <div id="hilos">
        <div class="contenedorHilos">
            <p class="subtittleHijos">Registro Logins</p>
            <div class="auxScrollBar">
                <table id="tabla1" class="tablaRegistros" >
                    <thead>
                        <tr id="cabezeraTabla1">
                            <th>Nivel Riesgo</th>
                            <th>Fecha</th>
                            <th>Dirección IP</th>
                            <th>Descripcion</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for log in recent_logs %}
                        <tr>
                            <td>{{ log.get_risk_level_display }}</td>
                            <td>{{ log.timestamp|date:"d F" }}</td>
                            <td>{{ log.ip_address }}</td>
                            <td>{{ log.description }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">No recent logs found.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <button id="btnAgregar">Agregar fila</button>
        </div>
        <div class="contenedorHilos">
            <p class="subtittleHijos">Eventos</p>
            <div class="auxScrollBar">
                <table id="tabla2" class="tablaEstadisticas">
                   <thead>
                                <tr>
                                    <th>Tipo de eventos</th>
                                    <th>Numero de incidencias</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Staff Accessed Account</td>
                                    <td>{{ staff_access_count }}</td>
                                </tr>
                                <tr>
                                    <td>Failed Staff Login Attempt</td>
                                    <td>{{ staff_failed_login }}</td>
                                </tr>
                                <tr>
                                    <td>Failed User Login Attempt</td>
                                    <td>{{ user_failed_login }}</td>
                                </tr>
                            </tbody>
                </table>
            </div>

        </div>
    </div>

    </div>

    <script>
          let arrow = document.querySelectorAll(".arrow");
          for (var i = 0; i < arrow.length; i++) {
            arrow[i].addEventListener("click", (e)=>{
           let arrowParent = e.target.parentElement.parentElement;//selecting main parent of arrow
           arrowParent.classList.toggle("showMenu");
            });
          }
          let sidebar = document.querySelector(".sidebar");
          let sidebarBtn = document.querySelector(".bx-menu");
          console.log(sidebarBtn);
          sidebarBtn.addEventListener("click", ()=>{
            sidebar.classList.toggle("close");
          });
  </script>

    <script>

        // Gráfica de Dona
    var ctx2 = document.getElementById('myChart2').getContext('2d');
    var myDoughnutChart = new Chart(ctx2, {
        type: 'doughnut',
        data: {
            labels: ['Bajo', 'Medio', 'Alto'],
            datasets: [{
                label: 'Registros de incidentes',
                data: [{{ low_risk_count }},
                    {{ medium_risk_count }},
                    {{ high_risk_count }},
                ],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(54, 162, 235, 0.6)',
                    'rgba(255, 206, 86, 0.6)',
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(153, 102, 255, 0.6)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
        }
    });

    </script>

  <script>


    // Gráfica de Área Polar
    var ctx3 = document.getElementById('myChart3').getContext('2d');
    var myPolarAreaChart = new Chart(ctx3, {
        type: 'polarArea',
        data: {
            labels: ['Login Staff', 'Failed Login Staff', 'Failed user'],
            datasets: [{
                label: 'Descripción',
                data: [{{ staff_access_count }},
                        {{ staff_failed_login }},
                        {{ user_failed_login }},
                ],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(255, 206, 86, 0.6)',
                    'rgba(201, 203, 207, 0.6)',
                    'rgba(54, 162, 235, 0.6)'
                ]
            }]
        },
        options: {
            scales: {
                r: {
                    angleLines: {
                        display: false
                    },
                    suggestedMin: 0,
                    suggestedMax: 10
                }
            },
            responsive: true,
            maintainAspectRatio: false
        }
    });
  </script>

      <script>


    // Gráfica de Área Polar
    var ctx3 = document.getElementById('myChart4').getContext('2d');
    var myPolarAreaChart = new Chart(ctx3, {
        type: 'polarArea',
        data: {
            labels: ['Login Staff', 'Failed Login Staff', 'Failed user'],
            datasets: [{
                label: 'Descripción',
                data: [{{ staff_access_count }},
                        {{ staff_failed_login }},
                        {{ user_failed_login }},
                ],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(255, 206, 86, 0.6)',
                    'rgba(201, 203, 207, 0.6)',
                    'rgba(54, 162, 235, 0.6)'
                ]
            }]
        },
        options: {
            scales: {
                r: {
                    angleLines: {
                        display: false
                    },
                    suggestedMin: 0,
                    suggestedMax: 10
                }
            },
            responsive: true,
            maintainAspectRatio: false
        }
    });
  </script>


    <script>
    // Gráfica de Barras
    var ctx1 = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx1, {
        type: 'bar',
        data: {
            labels: ['Riesgo bajo', 'Riesgo medio', 'Riesgo alto'],
            datasets: [{
                label: 'Registro por niveles de riesgo',
                data: [{{ low_risk_count }},
                        {{ medium_risk_count }},
                        {{ high_risk_count }},
                ],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.4)',
                    'rgba(54, 162, 235, 0.4)',
                    'rgba(255, 206, 86, 0.4)',
                    'rgba(75, 192, 192, 0.4)',
                    'rgba(153, 102, 255, 0.4)',
                    'rgba(255, 159, 64, 0.4)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            },
            responsive: true,
            maintainAspectRatio: false
        }
    });
</script>
    <script>
    // Inicialización del carrusel con Slick
    $(document).ready(function(){
        $('.carrusel').slick({
            dots: true,
            infinite: true,
            speed: 300,
            slidesToShow: 2,
            slidesToScroll: 2
        });
    });
    </script>

<script>
    document.getElementById('btnAgregar').addEventListener('click', function() {
        var tabla = document.getElementById('tabla1').getElementsByTagName('tbody')[0];
        var nuevaFila = tabla.insertRow(tabla.rows.length);

        var celda1 = nuevaFila.insertCell(0);
        var celda2 = nuevaFila.insertCell(1);
        var celda3 = nuevaFila.insertCell(2);
        var celda4 = nuevaFila.insertCell(3);

        celda1.innerHTML = 'Nuevo dato 1';
        celda2.innerHTML = 'Nuevo dato 2';
        celda3.innerHTML = 'Nuevo dato 3';
        celda4.innerHTML = 'Nuevo dato 4';
    });
</script>
<script>
    document.getElementById('btnAgregar').addEventListener('click', function() {
        var tabla = document.getElementById('tabla2').getElementsByTagName('tbody')[0];
        var nuevaFila = tabla.insertRow(tabla.rows.length);

        var celda1 = nuevaFila.insertCell(0);
        var celda2 = nuevaFila.insertCell(1);
        var celda3 = nuevaFila.insertCell(2);
        var celda4 = nuevaFila.insertCell(3);

        celda1.innerHTML = 'Nuevo dato 1';
        celda2.innerHTML = 'Nuevo dato 2';
        celda3.innerHTML = 'Nuevo dato 3';

    });
    </script>

{% endblock contenido %}

templates/tickets1.html
{% extends 'base.html' %}

{% block contenido %}
<div class="bg-gray-100 text-gray-600 h-screen flex overflow-hidden text-sm">
  <div class="flex-grow overflow-hidden h-full flex flex-col">
      <div class="flex-grow bg-white overflow-y-auto">
        <div class="sm:px-7 sm:pt-7 px-4 pt-4 flex flex-col w-full border-b border-gray-200 bg-white sticky top-0">
          <div class="flex w-full items-center padding-center">
            <div class="flex items-center text-3xl text-gray-900">
              Security incidents
            </div>
          </div>
        </div>
        <div class="sm:p-7 p-4">
          <div class="flex w-full items-center mb-7">
            <button class="inline-flex mr-3 items-center h-8 pl-2.5 pr-2 rounded-md shadow text-gray-700 border-gray-200 leading-none py-0">
              <svg viewBox="0 0 24 24" class="w-4 mr-2 text-gray-400" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                <line x1="16" y1="2" x2="16" y2="6"></line>
                <line x1="8" y1="2" x2="8" y2="6"></line>
                <line x1="3" y1="10" x2="21" y2="10"></line>
              </svg>
              Last 30 days
              <svg viewBox="0 0 24 24" class="w-4 ml-1.5 text-gray-400" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </button>
            <button class="inline-flex items-center h-8 pl-2.5 pr-2 rounded-md shadow text-gray-700 border border-gray-200 leading-none py-0">
              Filter by
              <svg viewBox="0 0 24 24" class="w-4 ml-1.5 text-gray-400" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </button>
            <div class="ml-auto text-gray-500 text-xs sm:inline-flex hidden items-center">
              <span class="mr-3">Page 2 of 4</span>
              <button class="inline-flex mr-2 items-center h-8 w-8 justify-center text-gray-400 rounded-md shadow border border-gray-200 leading-none py-0">
                <svg class="w-4" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <polyline points="15 18 9 12 15 6"></polyline>
                </svg>
              </button>
              <button class="inline-flex items-center h-8 w-8 justify-center text-gray-400 rounded-md shadow border border-gray-200 leading-none py-0">
                <svg class="w-4" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <polyline points="9 18 15 12 9 6"></polyline>
                </svg>
              </button>
            </div>
          </div>
<table class="w-full text-left">
    <thead>
        <tr class="text-gray-400">
            <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200">Number</th>
            <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200">Risk Level</th>
            <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 hidden md:table-cell">Description</th>
            <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200 sm:text-gray-400 text-white">Source</th>
            <th class="font-normal px-3 pt-0 pb-3 border-b border-gray-200">State</th>
        </tr>
    </thead>
    <tbody class="text-gray-600">
        {% for log in risk_logs %}
        <tr>
            <td class="sm:p-3 py-2 px-1 border-b border-gray-200">
               <a href="{% url 'detalle_ticket' %}">{{ log.id }}</a>
            </td>
            <td class="sm:p-3 py-2 px-1 border-b border-gray-200 text-red-500" style="color: {% if log.risk_level == 'low' %}blue{% elif log.risk_level == 'medium' %}orange{% else %}red{% endif %};">{{ log.get_risk_level_display }}</td>
            <td class="sm:p-3 py-2 px-1 border-b border-gray-200 md:table-cell hidden">{{ log.description }}</td>
            <td class="sm:p-3 py-2 px-1 border-b border-gray-200">{{ log.ip_address }}</td>
            <td class="sm:p-3 py-2 px-1 border-b border-gray-200">{{ log.status }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5" class="text-center py-3">No risk logs found.</td>
        </tr>
        {% endfor %}
        {% for entry in log_entry %}
            <tr>
                <td class="sm:p-3 py-2 px-1 border-b border-gray-200">{{ entry.line_id }}</td>
                <td class="sm:p-3 py-2 px-1 border-b border-gray-200 text-red-500" style="color: {% if entry.level == 'WARNING' %}blue{% elif entry.level == 'ERROR' %}orange{% else %}red{% endif %};">{{entry.risk_level}}</td>
                <td class="sm:p-3 py-2 px-1 border-b border-gray-200 md:table-cell hidden">{{ entry.process}}</td>
                <td class="sm:p-3 py-2 px-1 border-b border-gray-200">172.28.150.54</td>
                <td class="sm:p-3 py-2 px-1 border-b border-gray-200"></td>

            </tr>
        {% endfor %}
    </tbody>
</table>

          <div class="flex w-full mt-5 space-x-2 justify-end">
            <button class="inline-flex items-center h-8 w-8 justify-center text-gray-400 rounded-md shadow border border-gray-200 leading-none">
              <svg class="w-4" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="15 18 9 12 15 6"></polyline>
              </svg>
            </button>
            <button class="inline-flex items-center h-8 w-8 justify-center text-gray-500 rounded-md shadow border border-gray-200 leading-none">1</button>
            <button class="inline-flex items-center h-8 w-8 justify-center text-gray-500 rounded-md shadow border border-gray-200 bg-gray-100 dark:bg-gray-800 dark:text-white leading-none">2</button>
            <button class="inline-flex items-center h-8 w-8 justify-center text-gray-500 rounded-md shadow border border-gray-200 leading-none">3</button>
            <button class="inline-flex items-center h-8 w-8 justify-center text-gray-500 rounded-md shadow border border-gray-200 leading-none">4</button>
            <button class="inline-flex items-center h-8 w-8 justify-center text-gray-400 rounded-md shadow border border-gray-200 leading-none">
              <svg class="w-4" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="9 18 15 12 9 6"></polyline>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock contenido %}